-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Player"
(
    name character varying(80) NOT NULL,
    id integer NOT NULL,
    password bit varying,
    PRIMARY KEY (id)
);

CREATE TABLE public."Games"
(
    title character varying(80) NOT NULL,
    g_id integer NOT NULL,
    PRIMARY KEY (g_id)
);

CREATE TABLE public."Records"
(
    id integer NOT NULL,
    g_id integer NOT NULL,
    record integer NOT NULL,
    PRIMARY KEY (id, g_id)
);

ALTER TABLE public."Records"
    ADD FOREIGN KEY (id)
    REFERENCES public."Player" (id)
    NOT VALID;


ALTER TABLE public."Records"
    ADD FOREIGN KEY (g_id)
    REFERENCES public."Games" (g_id)
    NOT VALID;

END;